//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace CarRentalTestApp.DatabaseWebRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LINQDatabaseSoap", Namespace="http://tempuri.org/")]
    public partial class LINQDatabase : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveBookingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LINQDatabase() {
            this.Url = global::CarRentalTestApp.Properties.Settings.Default.CarRentalTestApp_DatabaseWebRef_LINQDatabase;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveCustomerCompletedEventHandler SaveCustomerCompleted;
        
        /// <remarks/>
        public event GetReviewCompletedEventHandler GetReviewCompleted;
        
        /// <remarks/>
        public event SaveBookingCompletedEventHandler SaveBookingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveCustomer(Customer c) {
            object[] results = this.Invoke("SaveCustomer", new object[] {
                        c});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveCustomerAsync(Customer c) {
            this.SaveCustomerAsync(c, null);
        }
        
        /// <remarks/>
        public void SaveCustomerAsync(Customer c, object userState) {
            if ((this.SaveCustomerOperationCompleted == null)) {
                this.SaveCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCustomerOperationCompleted);
            }
            this.InvokeAsync("SaveCustomer", new object[] {
                        c}, this.SaveCustomerOperationCompleted, userState);
        }
        
        private void OnSaveCustomerOperationCompleted(object arg) {
            if ((this.SaveCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCustomerCompleted(this, new SaveCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReview", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReviewModel GetReview(int vehicle_id) {
            object[] results = this.Invoke("GetReview", new object[] {
                        vehicle_id});
            return ((ReviewModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetReviewAsync(int vehicle_id) {
            this.GetReviewAsync(vehicle_id, null);
        }
        
        /// <remarks/>
        public void GetReviewAsync(int vehicle_id, object userState) {
            if ((this.GetReviewOperationCompleted == null)) {
                this.GetReviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReviewOperationCompleted);
            }
            this.InvokeAsync("GetReview", new object[] {
                        vehicle_id}, this.GetReviewOperationCompleted, userState);
        }
        
        private void OnGetReviewOperationCompleted(object arg) {
            if ((this.GetReviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReviewCompleted(this, new GetReviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveBooking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveBooking(Booking b) {
            object[] results = this.Invoke("SaveBooking", new object[] {
                        b});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveBookingAsync(Booking b) {
            this.SaveBookingAsync(b, null);
        }
        
        /// <remarks/>
        public void SaveBookingAsync(Booking b, object userState) {
            if ((this.SaveBookingOperationCompleted == null)) {
                this.SaveBookingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveBookingOperationCompleted);
            }
            this.InvokeAsync("SaveBooking", new object[] {
                        b}, this.SaveBookingOperationCompleted, userState);
        }
        
        private void OnSaveBookingOperationCompleted(object arg) {
            if ((this.SaveBookingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveBookingCompleted(this, new SaveBookingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer {
        
        private int customer_idField;
        
        private string first_nameField;
        
        private string last_nameField;
        
        private int ageField;
        
        private char genderField;
        
        private string emailField;
        
        private string phone_numberField;
        
        private string addressField;
        
        private string cityField;
        
        private Booking[] bookingsField;
        
        /// <remarks/>
        public int customer_id {
            get {
                return this.customer_idField;
            }
            set {
                this.customer_idField = value;
            }
        }
        
        /// <remarks/>
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
            }
        }
        
        /// <remarks/>
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        public int age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public char gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                this.phone_numberField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public Booking[] Bookings {
            get {
                return this.bookingsField;
            }
            set {
                this.bookingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Booking {
        
        private int booking_idField;
        
        private string booking_status_codeField;
        
        private int customer_idField;
        
        private int vehicle_idField;
        
        private System.DateTime pickup_dateField;
        
        private System.DateTime return_dateField;
        
        private string pickup_cityField;
        
        private string return_cityField;
        
        private BookingStatus bookingStatusField;
        
        private Customer customerField;
        
        private Vehicle vehicleField;
        
        /// <remarks/>
        public int booking_id {
            get {
                return this.booking_idField;
            }
            set {
                this.booking_idField = value;
            }
        }
        
        /// <remarks/>
        public string booking_status_code {
            get {
                return this.booking_status_codeField;
            }
            set {
                this.booking_status_codeField = value;
            }
        }
        
        /// <remarks/>
        public int customer_id {
            get {
                return this.customer_idField;
            }
            set {
                this.customer_idField = value;
            }
        }
        
        /// <remarks/>
        public int vehicle_id {
            get {
                return this.vehicle_idField;
            }
            set {
                this.vehicle_idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pickup_date {
            get {
                return this.pickup_dateField;
            }
            set {
                this.pickup_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime return_date {
            get {
                return this.return_dateField;
            }
            set {
                this.return_dateField = value;
            }
        }
        
        /// <remarks/>
        public string pickup_city {
            get {
                return this.pickup_cityField;
            }
            set {
                this.pickup_cityField = value;
            }
        }
        
        /// <remarks/>
        public string return_city {
            get {
                return this.return_cityField;
            }
            set {
                this.return_cityField = value;
            }
        }
        
        /// <remarks/>
        public BookingStatus BookingStatus {
            get {
                return this.bookingStatusField;
            }
            set {
                this.bookingStatusField = value;
            }
        }
        
        /// <remarks/>
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle Vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BookingStatus {
        
        private string booking_status_codeField;
        
        private string booking_status_descriptionField;
        
        private Booking[] bookingsField;
        
        /// <remarks/>
        public string booking_status_code {
            get {
                return this.booking_status_codeField;
            }
            set {
                this.booking_status_codeField = value;
            }
        }
        
        /// <remarks/>
        public string booking_status_description {
            get {
                return this.booking_status_descriptionField;
            }
            set {
                this.booking_status_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Booking[] Bookings {
            get {
                return this.bookingsField;
            }
            set {
                this.bookingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReviewModel {
        
        private string registration_numberField;
        
        private string manufacturer_nameField;
        
        private string model_codeField;
        
        private string body_styleField;
        
        private bool automaticField;
        
        private int passenger_capacityField;
        
        private string vehicle_category_descriptionField;
        
        private string manufacturing_dateField;
        
        private int availabilityField;
        
        private decimal daily_rental_rateField;
        
        /// <remarks/>
        public string registration_number {
            get {
                return this.registration_numberField;
            }
            set {
                this.registration_numberField = value;
            }
        }
        
        /// <remarks/>
        public string manufacturer_name {
            get {
                return this.manufacturer_nameField;
            }
            set {
                this.manufacturer_nameField = value;
            }
        }
        
        /// <remarks/>
        public string model_code {
            get {
                return this.model_codeField;
            }
            set {
                this.model_codeField = value;
            }
        }
        
        /// <remarks/>
        public string body_style {
            get {
                return this.body_styleField;
            }
            set {
                this.body_styleField = value;
            }
        }
        
        /// <remarks/>
        public bool automatic {
            get {
                return this.automaticField;
            }
            set {
                this.automaticField = value;
            }
        }
        
        /// <remarks/>
        public int passenger_capacity {
            get {
                return this.passenger_capacityField;
            }
            set {
                this.passenger_capacityField = value;
            }
        }
        
        /// <remarks/>
        public string vehicle_category_description {
            get {
                return this.vehicle_category_descriptionField;
            }
            set {
                this.vehicle_category_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string manufacturing_date {
            get {
                return this.manufacturing_dateField;
            }
            set {
                this.manufacturing_dateField = value;
            }
        }
        
        /// <remarks/>
        public int availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
            }
        }
        
        /// <remarks/>
        public decimal daily_rental_rate {
            get {
                return this.daily_rental_rateField;
            }
            set {
                this.daily_rental_rateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VehicleCategory {
        
        private string vehicle_category_codeField;
        
        private string vehicle_category_descriptionField;
        
        private Vehicle[] vehiclesField;
        
        /// <remarks/>
        public string vehicle_category_code {
            get {
                return this.vehicle_category_codeField;
            }
            set {
                this.vehicle_category_codeField = value;
            }
        }
        
        /// <remarks/>
        public string vehicle_category_description {
            get {
                return this.vehicle_category_descriptionField;
            }
            set {
                this.vehicle_category_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle[] Vehicles {
            get {
                return this.vehiclesField;
            }
            set {
                this.vehiclesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Vehicle {
        
        private int vehicle_idField;
        
        private string registration_numberField;
        
        private string manufacturer_codeField;
        
        private string model_codeField;
        
        private string vehicle_category_codeField;
        
        private string manufacturing_dateField;
        
        private decimal daily_hire_rateField;
        
        private int availabilityField;
        
        private string current_cityField;
        
        private Booking[] bookingsField;
        
        private Manufacturer manufacturerField;
        
        private Model modelField;
        
        private VehicleCategory vehicleCategoryField;
        
        /// <remarks/>
        public int vehicle_id {
            get {
                return this.vehicle_idField;
            }
            set {
                this.vehicle_idField = value;
            }
        }
        
        /// <remarks/>
        public string registration_number {
            get {
                return this.registration_numberField;
            }
            set {
                this.registration_numberField = value;
            }
        }
        
        /// <remarks/>
        public string manufacturer_code {
            get {
                return this.manufacturer_codeField;
            }
            set {
                this.manufacturer_codeField = value;
            }
        }
        
        /// <remarks/>
        public string model_code {
            get {
                return this.model_codeField;
            }
            set {
                this.model_codeField = value;
            }
        }
        
        /// <remarks/>
        public string vehicle_category_code {
            get {
                return this.vehicle_category_codeField;
            }
            set {
                this.vehicle_category_codeField = value;
            }
        }
        
        /// <remarks/>
        public string manufacturing_date {
            get {
                return this.manufacturing_dateField;
            }
            set {
                this.manufacturing_dateField = value;
            }
        }
        
        /// <remarks/>
        public decimal daily_hire_rate {
            get {
                return this.daily_hire_rateField;
            }
            set {
                this.daily_hire_rateField = value;
            }
        }
        
        /// <remarks/>
        public int availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
            }
        }
        
        /// <remarks/>
        public string current_city {
            get {
                return this.current_cityField;
            }
            set {
                this.current_cityField = value;
            }
        }
        
        /// <remarks/>
        public Booking[] Bookings {
            get {
                return this.bookingsField;
            }
            set {
                this.bookingsField = value;
            }
        }
        
        /// <remarks/>
        public Manufacturer Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        public Model Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public VehicleCategory VehicleCategory {
            get {
                return this.vehicleCategoryField;
            }
            set {
                this.vehicleCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Manufacturer {
        
        private string manufacturer_codeField;
        
        private string manufacturer_nameField;
        
        private Vehicle[] vehiclesField;
        
        /// <remarks/>
        public string manufacturer_code {
            get {
                return this.manufacturer_codeField;
            }
            set {
                this.manufacturer_codeField = value;
            }
        }
        
        /// <remarks/>
        public string manufacturer_name {
            get {
                return this.manufacturer_nameField;
            }
            set {
                this.manufacturer_nameField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle[] Vehicles {
            get {
                return this.vehiclesField;
            }
            set {
                this.vehiclesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Model {
        
        private string model_codeField;
        
        private string body_styleField;
        
        private bool automaticField;
        
        private int passenger_capacityField;
        
        private Vehicle[] vehiclesField;
        
        /// <remarks/>
        public string model_code {
            get {
                return this.model_codeField;
            }
            set {
                this.model_codeField = value;
            }
        }
        
        /// <remarks/>
        public string body_style {
            get {
                return this.body_styleField;
            }
            set {
                this.body_styleField = value;
            }
        }
        
        /// <remarks/>
        public bool automatic {
            get {
                return this.automaticField;
            }
            set {
                this.automaticField = value;
            }
        }
        
        /// <remarks/>
        public int passenger_capacity {
            get {
                return this.passenger_capacityField;
            }
            set {
                this.passenger_capacityField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle[] Vehicles {
            get {
                return this.vehiclesField;
            }
            set {
                this.vehiclesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaveCustomerCompletedEventHandler(object sender, SaveCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetReviewCompletedEventHandler(object sender, GetReviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReviewModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReviewModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaveBookingCompletedEventHandler(object sender, SaveBookingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveBookingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveBookingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591