//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Practical2Task2.DatabaseServiceWebRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DatabaseServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DatabaseService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback fullNameExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback phoneExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback getContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback remindBirthdayOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DatabaseService() {
            this.Url = global::Practical2Task2.Properties.Settings.Default.Practical2Task2_DatabaseServiceWebRef_DatabaseService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event fullNameExistsCompletedEventHandler fullNameExistsCompleted;
        
        /// <remarks/>
        public event phoneExistsCompletedEventHandler phoneExistsCompleted;
        
        /// <remarks/>
        public event saveContactCompletedEventHandler saveContactCompleted;
        
        /// <remarks/>
        public event getContactCompletedEventHandler getContactCompleted;
        
        /// <remarks/>
        public event updateContactCompletedEventHandler updateContactCompleted;
        
        /// <remarks/>
        public event remindBirthdayCompletedEventHandler remindBirthdayCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fullNameExists", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool fullNameExists(string firstName, string lastName) {
            object[] results = this.Invoke("fullNameExists", new object[] {
                        firstName,
                        lastName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void fullNameExistsAsync(string firstName, string lastName) {
            this.fullNameExistsAsync(firstName, lastName, null);
        }
        
        /// <remarks/>
        public void fullNameExistsAsync(string firstName, string lastName, object userState) {
            if ((this.fullNameExistsOperationCompleted == null)) {
                this.fullNameExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfullNameExistsOperationCompleted);
            }
            this.InvokeAsync("fullNameExists", new object[] {
                        firstName,
                        lastName}, this.fullNameExistsOperationCompleted, userState);
        }
        
        private void OnfullNameExistsOperationCompleted(object arg) {
            if ((this.fullNameExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fullNameExistsCompleted(this, new fullNameExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/phoneExists", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool phoneExists(string phone) {
            object[] results = this.Invoke("phoneExists", new object[] {
                        phone});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void phoneExistsAsync(string phone) {
            this.phoneExistsAsync(phone, null);
        }
        
        /// <remarks/>
        public void phoneExistsAsync(string phone, object userState) {
            if ((this.phoneExistsOperationCompleted == null)) {
                this.phoneExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnphoneExistsOperationCompleted);
            }
            this.InvokeAsync("phoneExists", new object[] {
                        phone}, this.phoneExistsOperationCompleted, userState);
        }
        
        private void OnphoneExistsOperationCompleted(object arg) {
            if ((this.phoneExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.phoneExistsCompleted(this, new phoneExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/saveContact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool saveContact() {
            object[] results = this.Invoke("saveContact", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void saveContactAsync() {
            this.saveContactAsync(null);
        }
        
        /// <remarks/>
        public void saveContactAsync(object userState) {
            if ((this.saveContactOperationCompleted == null)) {
                this.saveContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveContactOperationCompleted);
            }
            this.InvokeAsync("saveContact", new object[0], this.saveContactOperationCompleted, userState);
        }
        
        private void OnsaveContactOperationCompleted(object arg) {
            if ((this.saveContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveContactCompleted(this, new saveContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getContact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getContact() {
            this.Invoke("getContact", new object[0]);
        }
        
        /// <remarks/>
        public void getContactAsync() {
            this.getContactAsync(null);
        }
        
        /// <remarks/>
        public void getContactAsync(object userState) {
            if ((this.getContactOperationCompleted == null)) {
                this.getContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetContactOperationCompleted);
            }
            this.InvokeAsync("getContact", new object[0], this.getContactOperationCompleted, userState);
        }
        
        private void OngetContactOperationCompleted(object arg) {
            if ((this.getContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getContactCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateContact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateContact() {
            this.Invoke("updateContact", new object[0]);
        }
        
        /// <remarks/>
        public void updateContactAsync() {
            this.updateContactAsync(null);
        }
        
        /// <remarks/>
        public void updateContactAsync(object userState) {
            if ((this.updateContactOperationCompleted == null)) {
                this.updateContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateContactOperationCompleted);
            }
            this.InvokeAsync("updateContact", new object[0], this.updateContactOperationCompleted, userState);
        }
        
        private void OnupdateContactOperationCompleted(object arg) {
            if ((this.updateContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateContactCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/remindBirthday", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void remindBirthday() {
            this.Invoke("remindBirthday", new object[0]);
        }
        
        /// <remarks/>
        public void remindBirthdayAsync() {
            this.remindBirthdayAsync(null);
        }
        
        /// <remarks/>
        public void remindBirthdayAsync(object userState) {
            if ((this.remindBirthdayOperationCompleted == null)) {
                this.remindBirthdayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremindBirthdayOperationCompleted);
            }
            this.InvokeAsync("remindBirthday", new object[0], this.remindBirthdayOperationCompleted, userState);
        }
        
        private void OnremindBirthdayOperationCompleted(object arg) {
            if ((this.remindBirthdayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.remindBirthdayCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void fullNameExistsCompletedEventHandler(object sender, fullNameExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fullNameExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fullNameExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void phoneExistsCompletedEventHandler(object sender, phoneExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class phoneExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal phoneExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void saveContactCompletedEventHandler(object sender, saveContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getContactCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void updateContactCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void remindBirthdayCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591